### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_variables'

### ISSUE THREAD

**Issue by dj-wasabi** [jhoekx/ansible-yaml-inventory#1]
Hi there,

I' trying to use your  file for our setup. 

We have an environment group name, like development. Each environment has 2 different kinds of groups, in this case development_fe and development_be. Each group has 1 or more hosts entries.

I have the following hosts.yml

```

---

- host: development_frontend_01
  vars:
  - admin_ip: 192.168.1.2

- host: development_backend_01
  vars:
  - admin_ip: 192.168.1.3

- group: development
  groups:
  - development_fe
  - development_be

- group: development_fe
  hosts:
  - development_frontend_01

- group: development_be
  hosts:
  - development_backend_01
```

But when I run it, I get the following message:

```
./yaml-hosts.py -H development
Traceback (most recent call last):
  File "./yaml-hosts.py", line 247, in <module>
    result = host.get_variables()
AttributeError: 'NoneType' object has no attribute 'get_variables'
```

What am I doing wrong?
Kind regards,

Werner
